services:
  app:
    container_name: react_vite_app
    build:
      context: .
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_EXPLORER_URL=${VITE_EXPLORER_URL}
      - VITE_NETWORK=${VITE_NETWORK}
